// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEvLsKZEiTiKVL8n2aW_K6CJhvbwFEsSc',
    appId: '1:669372528509:web:69cf1e79020a972e79be14',
    messagingSenderId: '669372528509',
    projectId: 'tefillah-app-30c0d',
    authDomain: 'tefillah-app-30c0d.firebaseapp.com',
    storageBucket: 'tefillah-app-30c0d.firebasestorage.app',
    measurementId: 'G-7XRVRRRZ7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxvqYpk6ZLwN0sPwXW6yx63Uen0dwBU0w',
    appId: '1:669372528509:android:3efea6915d30166e79be14',
    messagingSenderId: '669372528509',
    projectId: 'tefillah-app-30c0d',
    storageBucket: 'tefillah-app-30c0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoi94XgVUXkkaaEkSSLy9nmjSd7V4tcPU',
    appId: '1:669372528509:ios:606e9890f336e92479be14',
    messagingSenderId: '669372528509',
    projectId: 'tefillah-app-30c0d',
    storageBucket: 'tefillah-app-30c0d.firebasestorage.app',
    iosClientId: '669372528509-v38hoalass0d3u9kjq4ha0gok794skkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tefillahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEvLsKZEiTiKVL8n2aW_K6CJhvbwFEsSc',
    appId: '1:669372528509:web:d3cdc84f393680a179be14',
    messagingSenderId: '669372528509',
    projectId: 'tefillah-app-30c0d',
    authDomain: 'tefillah-app-30c0d.firebaseapp.com',
    storageBucket: 'tefillah-app-30c0d.firebasestorage.app',
    measurementId: 'G-RMJJXD0XSZ',
  );

}